using System.Collections.Generic;
using System.Windows;
using System.Windows.Input;

namespace IMS
{
    /// <summary>
    /// Interaction logic for ReservedUsersInfoWindow.xaml
    /// </summary>
    public partial class ReservedUsersInfoWindow : Window
    {
        public ReservedUsersInfoWindow()
        {
            InitializeComponent();
            PopulateUsersList(); // Call this method when the window is initialized
        }

        private void OkButton_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        private void Window_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (e.ChangedButton == MouseButton.Left)
            {
                this.DragMove();
            }
        }

        private void PopulateUsersList()
        {
            List<string> users = new List<string>
            {
                "SM_2a41209de9bf42458/SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}",
                "Hiba.Mardini/Hiba Mardini",
                "Mamoon.AbuBajah/Mamoon AbuBajah",
                "haitham.abdelqader/Haitham Abdelqader",
                "Amjad.Walweel/Amjad Walweel",
                "Husam.Khalili/Husam Khalili",
                "Naziha.Zenim/Naziha Zenim",
                "Mazen.Daher/Mazen Daher",
                "Suha.Gadieh/Suha Gadieh",
                "Mohammad.Sharif/Mohammad Sharif",
                "Waleed.AbuTahoon/Waleed AbuTahoon",
                "Kefaya.Jibreel/Kefaya Jibreel",
                "Khaled.AbuAisheh/Khaled Abu Aisheh",
                "Amjad.AbuAabed/Amjad AbuAabed",
                "Maher.Ibraheem/Maher Ibraheem",
                "Rasheed.AbuLebdeh/Rasheed AbuLebdeh",
                "Marwan.Sharqawi/Marwan Sharqawi",
                "Mohammad.Yousef/Mohammad Yousef",
                "zaid.mobaydeen/Zaid Mobaydeen",
                "Maysoon.Jibreel/Maysoon Jibreel",
                "Yaseen.Odeh/Yaseen Odeh",
                "qc.alshahm/QC",
                "Lutfi.Kanaan/Lutfi Kanaan",
                "Marwan.Abdelwahab/Marwan Abdelwahab",
                "Husam.Abed/Husam Abed",
                "Taha.Mahjoob/Taha Mahjoob",
                "Careers/Careers",
                "Khaled.Sumreen/Khaled Sumreen",
                "Waleed.Azar/Waleed Azar",
                "Mohammad.Odeh/Mohammad Odeh",
                "Radi.Hannon/Radi Hannon",
                "Jawad.Badawi/Jawad Badawi",
                "Khaldoun.Jawhar/Khaldoun Jawhar",
                "Khaled.Muhsen/Khaled Muhsen",
                "Eisa.Ahmad/Eisa Ahmad",
                "Mahmoud.Abboushi/Mahmoud Abboushi",
                "Osama.Mabroum/Osama Mabroum",
                "SP_UserSync/SP_UserSync",
                "Ahmad.audh/Ahmad audh",
                "Rami.Qendeel/Rami Qendeel",
                "MR1/Meeting Room 1",
                "Maher.Shalameesh/Maher Shalameesh",
                "Walid.Ghunaim/Walid Ghunaim",
                "Huthaifah.Ghalban/Huthaifah Ghalban",
                "Lama.Moubaydeen/Lama Moubaydeen",
                "HR/HR",
                "Mahmoud.Tawalbeh/Mahmoud Tawalbeh",
                "Salaam.Otoum/Salaam Otoum",
                "Nabeel.Thebyan/Nabeel Thebyan",
                "Mohammad.Sawalha/Mohammad Sawalha",
                "Mahmoud.Azzeh/Mahmoud Azzeh",
                "Amr.mohammad/Amr Mohammad",
                "Omar.Jbr/Omar Jbr",
                "InfoBDR/Info",
                "Ali.akayleh/Ali akayleh",
                "shj.warehouse/shj.warehouse",
                "Mohammad.Ayasreh/Mohammad Ayasreh",
                "SALEM.SALEM/SALEM SALEM",
                "infogulfpearl/Info",
                "Hussein.Ghosheh2/Hussein Ghosheh",
                "fawaz.alkhamaiseh/Fawaz Alkhamaiseh",
                "Mohammad.Ansari/Mohammad Ansari",
                "Nicolas.Machado/Nicolas Machado",
                "Mohamed.Rahim/Mohamed Rahim",
                "Rashid.Hanif/Rashid Hanif",
                "Waseem.Maoed/Waseem Maoed",
                "SP_Admin/SP_Admin",
                "Malek.Hayajneh/Malek Hayajneh",
                "Ibrahim.Abuhelal/Ibrahim Abuhelal",
                "Jorinteg/Jorinteg",
                "Hussein.Ghosheh3/Hussein Ghosheh",
                "Sam.Shadfan/sam shadfan",
                "scan_ef/scan_ef",
                "Mohammad.kazkaz/Mohammad kazkaz",
                "Mohammad.AbuGhaush/Mohammad AbuGhaush",
                "Khalid.Breeji/Khalid Breeji",
                "Secretary1/Secretary1",
                "Mohammad.Salkhadi/Mohammad Salkhadi",
                "Attallah.eid/Attallah eid",
                "Mohammad.Suliman/Mohammad Suliman",
                "Mohammad.audih/Mohammad audih",
                "Hamza.khalid/Hamza khalid",
                "Sami.Ammar/Sami Ammar",
                "Bilal.Farhi/Bilal Farhi",
                "Raed.Alroasan/Raed Alroasan",
                "Wesam.Eryan/Wesam Eryan",
                "its/its",
                "Mohammad.Alsahouri/Mohammad Alsahouri",
                "Tarek.AbdelRahman/Tarek Abdel Rahman",
                "Saddam.Alrawashdeh/Saddam Alrawashdeh",
                "Mohammad.Jarireh/Mohammad Jarireh",
                "Samar.Khayata/Samar Khayata",
                "Mahmoud.Mustafa/Mahmoud Mustafa",
                "Hana.Ibrahim/Hana Ibrahim",
                "Rasem.Abumadi/Rasem Abu Madi",
                "Hashem.Farajat/Hashem Farajat",
                "Bayan.Hussen/Bayan Hussen",
                "Mustafa.Faisal/Mustafa Faisal",
                "Jafaar.Abuhwoedi/Jafaar Abuhwoedi",
                "Mulki.Mujali/Mulki Mujali",
                "Rawan.Shamlouli/Rawan Shamlouli",
                "Amer.Huneidi/Amer Huneidi",
                "Alaa.Awad/Alaa Awad",
                "Amneh.Abed/Amneh Abed",
                "LMS/LMS",
                "Mohammad.Saad/Mohammad Saad",
                "Nancy.kouyoumjian/Nancy kouyoumjian",
                "Nadeem.Ishtiaq/Nadeem Ishtiaq",
                "Simon.Benjamin/Simon Benjamin",
                "Ibrahim.Abulebdeh/Ibrahim Abulebdeh",
                "SQLAnalysisAcct/SQLAnalysisAcct",
                "Samira.husenova/Samira husenova",
                "SM_639daa915a094360a/FederatedEmail.4c1f4d8b-8179-4148-93bf-00a95fa1e042",
                "Mohammad.tarawneh/Mohammad Tarawneh",
                "Nayib.Seluja/Nayib Seluja",
                "Mohammad.Safi/Mohammad Safi",
                "Suhail.Kharbat2/Suhail Kharbat",
                "RIZAN.JURANGPATHY/RIZAN JURANGPATHY",
                "Mohammad.Amin/Mohammad Amin",
                "Ayed.Shawkat/Ayed Shawkat",
                "Jawad.Wazani/Jawad Wazani",
                "Hussein.Ghayadah/Hussein Ghayadah",
                "Yahya.Ghosheh/Yahya Ghosheh",
                "Khaled.Okkeh/Khaled Okkeh",
                "Tariq.Hijazi/Tariq Hijazi",
                "Ali.Nashash/Ali Nashash",
                "Salman.Chandna/Salman Chandna",
                "Omar.Naqawa/Omar Naqawa",
                "Santhosh.Paruvayakot/Santhosh Paruvayakottil",
                "admin_m/SRV_SystemDIS",
                "Sami.Naser/Sami Naser",
                "Mahmoud.Ghourani/Mahmoud Ghourani",
                "Hussein.Ghosheh/Hussein Ghosheh",
                "Othman.Mahasneh/Othman Mahasneh",
                "Mustafa.Ghunaim/Mustafa Ghunaim",
                "Mohammad.Momani/Mohammad Momani",
                "Samer.Ramadan/Samer Ramadan",
                "HG/HG",
                "Suhail.Kharbat/Suhail Kharbat",
                "Mohammad.Hasan/Mohammad Hasan",
                "Mohammad.Hijazi/Mohammad Hijazi",
                "Fawaz.Dibis/Fawaz Dibis",
                "Marwan.Abdulrahman/Marwan Abdulrahman",
                "Omran.Khalaf/Omran Khalaf",
                "Hanadi.Quqa/Hanadi Quqa",
                "Naveed.Iqbal/Naveed Iqbal",
                "Mahmoud.Dolani/Mahmoud Dolani",
                "Nizar.Darwish/Nizar Darwish",
                "fax/Fax",
                "Issam.Hijazi/Issam Hijazi",
                "Mohammad.Othman/Mohammad Othman",
                "Amer.Omari/Amer Omari",
                "Hani.Hijazi/Hani Hijazi",
                "kenoz/kenoz",
                "Mohammad.AbuDiah/Mohammad AbuDiah",
                "Moayyad.Doomy/Moayyad Doomy",
                "WebAdmin/WebAdmin",
                "Wafa.Hindy/Wafa Hindy",
                "Mamoon.Bakeer/Mamoon Bakeer",
                "Rana.Abed/Rana Abed",
                "Saber.Badayneh/Saber Badayneh",
                "info/Info",
                "Hasan.Daraghmeh/Hasan Daraghmeh",
                "Tariq.Swailem/Tariq Swailem",
                "Firas.Khader/Firas Khader",
                "Raed.Awad/Raed Awad",
                "SP_Farm/SP_Farm",
                "Ali.Odeh/Ali Odeh",
                "Sameh.Helal/Sameh Helal",
                "Mehdi.Hamadneh/Mehdi Hamadneh",
                "Hasan.AbuTahoon/Hasan AbuTahoon",
                "Ibrahim.Mobydeen/Ibrahim Mobydeen",
                "Mahmoud.AbuHweej/Mahmoud Abu Hweej",
                "Ahmad.Rabaa/Ahmad Rabaa",
                "Mohammad.AbuDawas/Mohammad AbuDawas",
                "Emran.AbuElhawa/Emran AbuElhawa",
                "Hazem.Jarrar/Hazem Jarrar",
                "Mohammad.Hasanain/Mohammad Hasanain",
                "Rami.Hemsy/Rami Hemsy",
                "Hani.Kayyali/Hani Kayyali",
                "Jalal.Deek/Jalal Deek",
                "Mohammad.Ateya/Mohammad Ateya",
                "Hosam.Ashhab/Hosam Ashhab",
                "Hatem.AbuTahoon/Hatem AbuTahoon",
                "Mohammad.Momany/Mohammad Momany",
                "Amjad.assaf/Amjad Assaf",
                "Reham.Aqrabawy/Reham Aqrabawy",
                "Basem.Shadfan/Basem Shadfan",
                "Mohammad.Khamees/Mohammad Khamees",
                "Jamal.Saleh/Jamal Saleh",
                "Ismail.Hussein/Ismail Hussein",
                "Salah.Salamat/Salah Salamat",
                "Mohammad.Khaild/Mohammad Khaild",
                "CEO/Issam Hijazi",
                "Rami.Omari/Rami Omari",
                "Nazzal.wreikat/Nazzal Wreikat",
                "Scan/Scan - X1",
                "Monitor/Monitor",
                "Rami.Ajeeb/Rami Ajeeb",
                "Eyad.Mahdi/Eyad Mahdi",
                "Razan.Hiasat/Razan Hiasat",
                "Mohammad.Hijawi/Mohammad Hijawi",
                "Sameer.Namous/Sameer Namous",
                "Hamza.Qahwaji/Hamza Qahwaji",
                "Nadia.Abbas/Nadia Abbas",
                "QwairahStores/Qwairah Stores",
                "docs/docs",
                "IT.Support/IT.Support",
                "Armie.Kalaw/Armie Kalaw",
                "MarineTraffic/MarineTraffic",
                "Nabila.Zahani/Nabila Zahani",
                "Oussama.Nahnouh/Oussama Nahnouh",
                "Samia.AbuAwad/Samia AbuAwad",
                "Nizar.Sarieddin/Nizar Sarrieddin",
                "helpdesk/helpdesk",
                "Odai.Hoseh/Odai Hoseh",
                "Mahmoud.Qurani/Mahmoud Qurani",
                "Ziad.Qatanani/Ziad Qatanani",
                "Mohammad.Moghis/Mohammad Moghis",
                "lPurchasing.alshahm/Local Purchasing",
                "Accounting.alshahm/Accounting",
                "Mohammad.Hasanain2/Mohammad Hasanain",
                "Mahmoud.AbdulMawla/Mahmoud Abdul Mawla",
                "Warehouse.alshahm/Warehouse",
                "Suhail.Kharbat3/Suhail Kharbat",
                "lsales.alshahm/Local Sales",
                "Ahmad.Jabaie2/Ahmad Jabaie",
                "Hosam.Issa/Hosam Issa",
                "Taha.Hammad/Taha Hammad",
                "Moath.Qazaah/Moath Qazaah",
                "mohammad.sarayrah/Mohammad Sarayrah",
                "Zakaria.Wazani/Zakaria Wazani",
                "Naela.Maaita/Naela Maaita",
                "Mohammad.Akram/Mohammad Akram",
                "SRVSQL/SRVSQL",
                "Mojahed.sadi/Mojahed sadi",
                "SRVAPP/SRVAPP",
                "sermon/sermon",
                "Tariq.Abooshi/Tariq Abooshi",
                "Syed.Asghar/Syed Asghar",
                "Devicelock/Devicelock",
                "Mohammad.Kafi/Mohammad Kafi",
                "Anwar.Maharmeh/Anwar Maharmeh",
                "Jamal.Badran/Jamal Badran",
                "Mohannad.Omari/Mohannad Omari",
                "Razan.Saras/Razan Saras",
                "Ala.Shanableh/Ala Shanableh",
                "Raymon.Dayson/Raymon Dayson",
                "Mohammad.Qaimary/Mohammad Qaimary",
                "Ibrahim.Ata/Ibrahim Ata",
                "RMS/RMS",
                "Social/Social",
                "miraship/Marine",
                "Bayan.Hasan/Bayan Hasan",
                "Ashraf.Hasan/Ashraf Hasan",
                "Laith.Momani/Laith Momani",
                "Mohammad.AbuSalem/Mohammad AbuSalem",
                "Mohammad.AbdelRahman/Mohammad Abdel Rahman",
                "Alaa.Mubasher/Alaa Mubasher",
                "ahmad.qasem/ahmad qasem",
                "husam.sharqawi/husam sharqawi",
                "Jihad.Ghool/Jihad Ghool",
                "Rawan.Sbaihat/Rawan Sbaihat",
                "Ahmad.Jabaie/Ahmad Jabaie",
                "Amer.Asmar/Amer.Asmar",
                "Bahaa.Bahnasi/Bahaa Bahnasi",
                "Ali.Bouriny/Ali Bouriny",
                "Ali.Qendeel/Ali Qendeel",
                "Ehab.AbuSel/Ehab AbuSel",
                "jafar.awadallah/jafar awadallah",
                "Motasem.sqoor/Motasem sqoor",
                "Dawood.AbuElkbash/Dawood AbuElkbash",
                "Abdullah.AbuZuhair/Abdullah AbuZuhair",
                "Sawsan.Saed/Sawsan saed",
                "Baker.Fahmi/Baker Fahmi",
                "Ahmad.Kafafi/Ahmad Kafafi",
                "Nader.abuaisheh/Nader abuaisheh",
                "Ola.Mwafi/Ola Mwafi",
                "Fadi.Badran/Fadi Badran",
                "Asaad.Radi/Asaad Radi",
                "Doa.AbuErshaid/Doa AbuErshaid",
                "Fayez.Mohammad/Fayez Mohammad",
                "Anas.Nassar/Anas Nassar",
                "Amer.Hijazi/Amer Hijazi",
                "abdullatif.Ibrahim/abdullatif Ibrahim",
                "Abdullah.Khlaifi/Abdullah Khlaifi",
                "Hamad.Bakeer/Hamad Bakeer",
                "Eman.AboSnober/Eman AboSnober",
                "Ayman.Hussein/Ayman Hussein",
                "Ahmad.AbuBaker/Ahmad AbuBaker",
                "Ala.Abdulhadi/Ala Abdulhadi",
                "Bassam.Mhedat/Bassam Mhedat",
                "Bassam.Saleh/Bassam Saleh",
                "Ebtisam.Aqrabawy/Ebtisam Aqrabawy",
                "Akram.AbuKhdair/Akram AbuKhdair",
                "Mahmoud.Daoud/Mahmoud Daoud",
                "Adnan.Dohaidy/Adnan Dohaidy",
                "Ali.Tawalbeh/Ali Tawalbeh",
                "OldApps/OldApps",
                "Khaled.Khudari/Khaled khudari",
                "QC.Dept/Qc Department",
                "Ahmad.Falaha/Ahmad Falaha",
                "Ahmad.Moubaydeen/Ahmad Moubaydeen",
                "OldAppsTest/OldAppsTest",
                "Emran.Khalaf/Emran Khalaf",
                "Eyad.AbuElrob/Eyad AbuElrob",
                "Riyadh.Dawaghreh/Riyadh Dawaghreh",
                "Fakhri.Akaailh/Fakhri Akaailh",
                "Fawaz.Ata/Fawaz Ata",
                "Ali.AbdulSamea/Ali AbdulSamea",
                "Mohammad.Abd/Mohammad Abd",
                "Naser.Saleh/Naser Saleh",
                "Ahmad.AbuFarah/Ahmad AbuFarah",
                "Safety/Safety",
                "Salman.Ali/Salman Ali",
                "Abdulkareem.Hanoon/Abdulkareem Hanoon",
                "Ayman.Saaidyn/Ayman Saaidyn",
                "Raed.Darweesh/Raed Darweesh",
                "Abed.Alqaissi/Abed Alqaissi",
                "Wael.Hijazi/Wael Hijazi",
                "Mamoun.Abu-Lubbad/Mamoun AbuLubbad",
                "Behzad.AbuDalal/Behzad AbuDalal",
                "Dudley.Leelananda/Dudley Leelananda",
                "Jad.Masoud/Jad Masoud",
                "Forat.Zoubi/Forat Zoubi",
                "Mahmoud.AbuEnein/Mahmoud AbuEnein",
                "Ala.Ghosheh/Ala Ghosheh",
                "Rami.Azaizeh/Rami Azaizeh",
                "SP_Crawl/SP_Crawl",
                "SP_WebApps/SP_WebApps",
                "Trainee/Trainee",
                "Firas.Ghosheh/Firas Ghosheh",
                "Mohammad.Kayed/Mohammad Kayed",
                "Osama.Khader/Osama Khader",
                "SM_f7e828e2c22f484f9/SystemMailbox{1f05a927-c503-43cd-a6a1-9549dce06497}",
                "Basem.Ghanem/Basem Ghanem",
                "Ryma.Hani/Ryma Hani",
                "Sami.AbuTaha/Sami Abu Taha",
                "Nadjet.Senoussi/Nadjet Senoussi"
            };

            // Bind the list of users to the ItemsSource of the ItemsControl
            UsersItemsControl.ItemsSource = users;
        }
    }
}